package server

import "fmt"

// GenerateContainerdConfig returns the content for /etc/containerd/config.toml.
// If socks5Proxy is set, registry.k8s.io and its GCP CDN are routed through it.
func GenerateContainerdConfig(sandboxImage, socks5Proxy string) string {
	proxySection := ""
	if socks5Proxy != "" {
		proxySection = fmt.Sprintf(`
[plugins."io.containerd.grpc.v1.cri".registry.configs."registry.k8s.io".transport]
  proxy_url = "socks5://%s"

[plugins."io.containerd.grpc.v1.cri".registry.configs."europe-west3-docker.pkg.dev".transport]
  proxy_url = "socks5://%s"
`, socks5Proxy, socks5Proxy)
	}
	return fmt.Sprintf(`# Generated by CasOS
version = 2

[plugins."io.containerd.grpc.v1.cri"]
  sandbox_image = %q
%s`, sandboxImage, proxySection)
}
